# Generated by Django 2.0.5 on 2018-08-20 05:30

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
        ('alerts', '0001_initial'),
        ('tasks', '0002_auto_20180819_0348'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskAlert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('status', models.IntegerField(choices=[(0, 'Inactive'), (1, 'Active')], default=1, verbose_name='status')),
                ('activate_date', models.DateTimeField(blank=True, help_text='keep empty for an immediate activation', null=True)),
                ('deactivate_date', models.DateTimeField(blank=True, help_text='keep empty for indefinite activation', null=True)),
                ('duration', models.IntegerField()),
                ('alert_status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='alerts.AlertStatus')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='categories.Category')),
                ('duration_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='alerts.Duration')),
                ('mode', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='alerts.Mode')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='tasks.Task')),
            ],
            options={
                'db_table': 'TaskAlert',
            },
        ),
    ]
