# Generated by Django 2.0.5 on 2018-08-20 09:29

from django.db import migrations, models
import tasks.models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_taskalert'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={},
        ),
        migrations.AlterField(
            model_name='task',
            name='ref_id',
            field=models.CharField(default=tasks.models.Task.generate_task_ref_id, max_length=13, unique=True),
        ),
    ]
